"""add topic fields and user_topics

Revision ID: 84c3cb6b8cca
Revises: 002_add_profile_fields
Create Date: 2026-04-28 02:00:56.053403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c3cb6b8cca'
down_revision: Union[str, Sequence[str], None] = '002_add_profile_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_topics_id'), 'user_topics', ['id'], unique=False)
    op.add_column('topics', sa.Column('category', sa.String(), nullable=False))
    op.add_column('topics', sa.Column('keywords', sa.JSON(), nullable=False))
    op.add_column('topics', sa.Column('excerpt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'excerpt')
    op.drop_column('topics', 'keywords')
    op.drop_column('topics', 'category')
    op.drop_index(op.f('ix_user_topics_id'), table_name='user_topics')
    op.drop_table('user_topics')
    # ### end Alembic commands ###
